steps:
  # Build container
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/coresec-app", "."]

  # Push to registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/coresec-app"]

  # Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - run
      - deploy
      - coresec-app
      - --image
      - gcr.io/$PROJECT_ID/coresec-app
      - --region
      - europe-west1
      - --platform
      - managed
      - --allow-unauthenticated

images:
  - gcr.io/$PROJECT_ID/coresec-app

options:
  logging: CLOUD_LOGGING_ONLY
